version: '3'

services:
  backend:
    container_name: backend
    build: ./backend
    ports:
      - '3000:3000'
    command: ["npm", "run", "start"]
    volumes:
      - "./backend:/usr/src/backend"
